# Generated by Django 5.2.3 on 2025-07-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='to_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('Paid', 'Paid')], max_length=20),
        ),
    ]
